### ISSUE TITLE
Hud not as photo 

### ISSUE THREAD

**Issue by ItsAegeus** [Obtaizen/qb-hud#1]
Just wanted to see what it was like in game. It’s a box hud and in cars hud does not load map just stays blank. Also all circles are black. Just wanted to let ya know.

**Comment by Obtaizen** [comment]
> Just wanted to see what it was like in game. It’s a box hud and in cars hud does not load map just stays blank. Also all circles are black. Just wanted to let ya know. 

I haven't heard any issues I'll look into it but your running the latest version of QBCore, correct?

**Comment by Dungonmast3r** [comment]
the error is with this line in the ui.html well thats what it shows for me. `  <script src="https://cdnjs.cloudflare.com/ajax/libs/progressbar.js/0.6.1/progressbar.min.js" integrity="sha512-7IoDEsIJGxz/gNyJY/0LRtS45wDSvPFXGPuC7Fo4YueWMNOmWKMAllEqo2Im3pgOjeEwsOoieyliRgdkZnY0ow==" crossorigin="anonymous"></script>
`
![Screenshot 2021-08-28 190422](https://user-images.githubusercontent.com/73086766/131226891-f693061d-04b7-4f05-be5f-f1e592f677a2.png)

**Comment by ItsAegeus** [comment]
> > Just wanted to see what it was like in game. It’s a box hud and in cars hud does not load map just stays blank. Also all circles are black. Just wanted to let ya know.
> 
> I haven't heard any issues I'll look into it but your running the latest version of QBCore, correct?

Dungo Has posted it before me but that's the one I get.

**Comment by macxitotruck** [comment]
not working same problem
