### ISSUE TITLE
Pressing B either only allows you to remove seatbelt or put on seatbelt, not both

### ISSUE THREAD

**Issue by Carmomeister** [Obtaizen/qb-hud#2]
So after testing out the recent version, when pressing "b" to put on belt, it kept saying "Removing the Seatbelt.." but after doing /+seatbelt to put on belt, anytime I press B, it now only does "putting on seatbelt" and not remove seatbelt

**Comment by Carmomeister** [comment]
**FIX:** Removed Seatbelt.lua from qb-smallrescources

**Comment by Obtaizen** [comment]
> So after testing out the recent version, when pressing "b" to put on belt, it kept saying "Removing the Seatbelt.." but after doing /+seatbelt to put on belt, anytime I press B, it now only does "putting on seatbelt" and not remove seatbelt

You need to remove your seatbelt.lua In qbsmallresources
