### ISSUE TITLE
not gaining or removing stress

### ISSUE THREAD

**Issue by TaKtic1aN** [Obtaizen/qb-hud#5]
client>stress.lua TriggerServerEvent('qb-hud:GainStress' should just be 'hud:GainStress' and 'hud:UpdateStress' need to drop the qb

**Comment by Obtaizen** [comment]
> client>stress.lua TriggerServerEvent('qb-hud:GainStress' should just be 'hud:GainStress' and 'hud:UpdateStress' need to drop the qb

Can you do a pull request I'm not home to fix this, or I'll fix when home.

**Comment by Obtaizen** [comment]
Fixed
