### ISSUE TITLE
Stress not getting gained

### ISSUE THREAD

**Issue by OfficialRDB** [Obtaizen/qb-hud#7]
Doesn't matter how hard i drive, there is not stress added.
Is there something else in the framework that has control over the stress ?

**Comment by Obtaizen** [comment]
You don't gain stress through driving fast or agressavily you just gain stress when shooting

**Comment by OfficialRDB** [comment]
> 
> 
> You don't gain stress through driving fast or agressavily you just gain stress when shooting

Alright, guess i have to add that myself. Tought it was a option. Thanks for the information.
